version: '3.8'

services:
  sqlserver:
    image: mi-sqlserver-personalizado  # Usa tu imagen personalizada de SQL Server
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=A12345678
      - SQLSERVER_TCP_PORT=1433
      - SQLSERVER_SSL_ENABLED=false  # Deshabilitar SSL (si es compatible con la versión)
    networks:
      - app-network

  api:
    image: ppi-challenge-api  # Tu API
    container_name: ppi-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PPI_CHALLENGE;User Id=sa;Password=A12345678;Encrypt=False;TrustServerCertificate=True;  # Asegúrate de no usar SSL
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
